name: Build Data Utils
on:
  push:
    branches: [master]
    paths:
    - json-data-utils/**
    - '!.github/workflows/**'
    - '!settings.gradle'
permissions:
  contents: read
jobs:
  build:
    uses: MinecraftForge/SharedActions/.github/workflows/gradle.yml@v0
    with:
      java: 21
      gradle_tasks: :json-data-utils:check :json-data-utils:publish
      project_path: json-data-utils
      artifact_name: json-data-utils
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      PROMOTE_ARTIFACT_WEBHOOK: ${{ secrets.PROMOTE_ARTIFACT_WEBHOOK }}
      PROMOTE_ARTIFACT_USERNAME: ${{ secrets.PROMOTE_ARTIFACT_USERNAME }}
      PROMOTE_ARTIFACT_PASSWORD: ${{ secrets.PROMOTE_ARTIFACT_PASSWORD }}
      MAVEN_USER: ${{ secrets.MAVEN_USER }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      GRADLE_CACHE_KEY: ${{ secrets.GRADLE_CACHE_KEY }}
