name: Build Log Utils
on:
  push:
    branches: [master]
    paths:
    - log-utils/**
    - '!.github/workflows/**'
    - '!settings.gradle'
permissions:
  contents: read
jobs:
  build:
    uses: MinecraftForge/SharedActions/.github/workflows/gradle.yml@v0
    with:
      java: 21
      gradle_tasks: :log-utils:check :log-utils:publish
      project_path: log-utils
      artifact_name: log-utils
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
